spring:
  application:
    name: settlement-batch

  datasource:
    url: jdbc:mysql://localhost:3306/batch
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  batch:
    jdbc:
      initialize-schema: never
    job:
      names: ${job.name:NONE}
      enabled: false

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
